/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RootLayoutRouteImport } from './routes/_rootLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RootLayoutProductsRouteImport } from './routes/_rootLayout/products'
import { Route as RootLayoutContactRouteImport } from './routes/_rootLayout/contact'
import { Route as RootLayoutAboutRouteImport } from './routes/_rootLayout/about'
import { Route as RootLayoutAuthRouteImport } from './routes/_rootLayout/_auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as RootLayoutAuthSignupRouteImport } from './routes/_rootLayout/_auth/signup'
import { Route as RootLayoutAuthLoginRouteImport } from './routes/_rootLayout/_auth/login'
import { Route as RootLayoutAuthForgetPasswordRouteImport } from './routes/_rootLayout/_auth/forget-password'

const RootLayoutRoute = RootLayoutRouteImport.update({
  id: '/_rootLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutProductsRoute = RootLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => RootLayoutRoute,
} as any)
const RootLayoutContactRoute = RootLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => RootLayoutRoute,
} as any)
const RootLayoutAboutRoute = RootLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RootLayoutRoute,
} as any)
const RootLayoutAuthRoute = RootLayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => RootLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutAuthSignupRoute = RootLayoutAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => RootLayoutAuthRoute,
} as any)
const RootLayoutAuthLoginRoute = RootLayoutAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RootLayoutAuthRoute,
} as any)
const RootLayoutAuthForgetPasswordRoute =
  RootLayoutAuthForgetPasswordRouteImport.update({
    id: '/forget-password',
    path: '/forget-password',
    getParentRoute: () => RootLayoutAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof RootLayoutAboutRoute
  '/contact': typeof RootLayoutContactRoute
  '/products': typeof RootLayoutProductsRoute
  '/forget-password': typeof RootLayoutAuthForgetPasswordRoute
  '/login': typeof RootLayoutAuthLoginRoute
  '/signup': typeof RootLayoutAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof RootLayoutAboutRoute
  '/contact': typeof RootLayoutContactRoute
  '/products': typeof RootLayoutProductsRoute
  '/forget-password': typeof RootLayoutAuthForgetPasswordRoute
  '/login': typeof RootLayoutAuthLoginRoute
  '/signup': typeof RootLayoutAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_rootLayout': typeof RootLayoutRouteWithChildren
  '/_rootLayout/_auth': typeof RootLayoutAuthRouteWithChildren
  '/_rootLayout/about': typeof RootLayoutAboutRoute
  '/_rootLayout/contact': typeof RootLayoutContactRoute
  '/_rootLayout/products': typeof RootLayoutProductsRoute
  '/_rootLayout/_auth/forget-password': typeof RootLayoutAuthForgetPasswordRoute
  '/_rootLayout/_auth/login': typeof RootLayoutAuthLoginRoute
  '/_rootLayout/_auth/signup': typeof RootLayoutAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/forget-password'
    | '/login'
    | '/signup'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/forget-password'
    | '/login'
    | '/signup'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_rootLayout'
    | '/_rootLayout/_auth'
    | '/_rootLayout/about'
    | '/_rootLayout/contact'
    | '/_rootLayout/products'
    | '/_rootLayout/_auth/forget-password'
    | '/_rootLayout/_auth/login'
    | '/_rootLayout/_auth/signup'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RootLayoutRoute: typeof RootLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_rootLayout': {
      id: '/_rootLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rootLayout/products': {
      id: '/_rootLayout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof RootLayoutProductsRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/_rootLayout/contact': {
      id: '/_rootLayout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof RootLayoutContactRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/_rootLayout/about': {
      id: '/_rootLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof RootLayoutAboutRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/_rootLayout/_auth': {
      id: '/_rootLayout/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutAuthRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rootLayout/_auth/signup': {
      id: '/_rootLayout/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof RootLayoutAuthSignupRouteImport
      parentRoute: typeof RootLayoutAuthRoute
    }
    '/_rootLayout/_auth/login': {
      id: '/_rootLayout/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof RootLayoutAuthLoginRouteImport
      parentRoute: typeof RootLayoutAuthRoute
    }
    '/_rootLayout/_auth/forget-password': {
      id: '/_rootLayout/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof RootLayoutAuthForgetPasswordRouteImport
      parentRoute: typeof RootLayoutAuthRoute
    }
  }
}

interface RootLayoutAuthRouteChildren {
  RootLayoutAuthForgetPasswordRoute: typeof RootLayoutAuthForgetPasswordRoute
  RootLayoutAuthLoginRoute: typeof RootLayoutAuthLoginRoute
  RootLayoutAuthSignupRoute: typeof RootLayoutAuthSignupRoute
}

const RootLayoutAuthRouteChildren: RootLayoutAuthRouteChildren = {
  RootLayoutAuthForgetPasswordRoute: RootLayoutAuthForgetPasswordRoute,
  RootLayoutAuthLoginRoute: RootLayoutAuthLoginRoute,
  RootLayoutAuthSignupRoute: RootLayoutAuthSignupRoute,
}

const RootLayoutAuthRouteWithChildren = RootLayoutAuthRoute._addFileChildren(
  RootLayoutAuthRouteChildren,
)

interface RootLayoutRouteChildren {
  RootLayoutAuthRoute: typeof RootLayoutAuthRouteWithChildren
  RootLayoutAboutRoute: typeof RootLayoutAboutRoute
  RootLayoutContactRoute: typeof RootLayoutContactRoute
  RootLayoutProductsRoute: typeof RootLayoutProductsRoute
}

const RootLayoutRouteChildren: RootLayoutRouteChildren = {
  RootLayoutAuthRoute: RootLayoutAuthRouteWithChildren,
  RootLayoutAboutRoute: RootLayoutAboutRoute,
  RootLayoutContactRoute: RootLayoutContactRoute,
  RootLayoutProductsRoute: RootLayoutProductsRoute,
}

const RootLayoutRouteWithChildren = RootLayoutRoute._addFileChildren(
  RootLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RootLayoutRoute: RootLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
