/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RootLayoutRouteImport } from './routes/_rootLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RootLayoutContactRouteImport } from './routes/_rootLayout/contact'
import { Route as RootLayoutAboutRouteImport } from './routes/_rootLayout/about'
import { Route as RootLayoutAuthRouteImport } from './routes/_rootLayout/_auth'
import { Route as RootLayoutProfileRouteRouteImport } from './routes/_rootLayout/profile/route'
import { Route as RootLayoutProductsIndexRouteImport } from './routes/_rootLayout/products/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as RootLayoutProfileWishlistRouteImport } from './routes/_rootLayout/profile/wishlist'
import { Route as RootLayoutProfileOverviewRouteImport } from './routes/_rootLayout/profile/overview'
import { Route as RootLayoutProfileAccountRouteImport } from './routes/_rootLayout/profile/account'
import { Route as RootLayoutProductsCartRouteImport } from './routes/_rootLayout/products/cart'
import { Route as RootLayoutProductsIdRouteImport } from './routes/_rootLayout/products/$id'
import { Route as RootLayoutAuthSignupRouteImport } from './routes/_rootLayout/_auth/signup'
import { Route as RootLayoutAuthLoginRouteImport } from './routes/_rootLayout/_auth/login'
import { Route as RootLayoutAuthForgetPasswordRouteImport } from './routes/_rootLayout/_auth/forget-password'

const RootLayoutRoute = RootLayoutRouteImport.update({
  id: '/_rootLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutContactRoute = RootLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => RootLayoutRoute,
} as any)
const RootLayoutAboutRoute = RootLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RootLayoutRoute,
} as any)
const RootLayoutAuthRoute = RootLayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => RootLayoutRoute,
} as any)
const RootLayoutProfileRouteRoute = RootLayoutProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RootLayoutRoute,
} as any)
const RootLayoutProductsIndexRoute = RootLayoutProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => RootLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutProfileWishlistRoute =
  RootLayoutProfileWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => RootLayoutProfileRouteRoute,
  } as any)
const RootLayoutProfileOverviewRoute =
  RootLayoutProfileOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => RootLayoutProfileRouteRoute,
  } as any)
const RootLayoutProfileAccountRoute =
  RootLayoutProfileAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => RootLayoutProfileRouteRoute,
  } as any)
const RootLayoutProductsCartRoute = RootLayoutProductsCartRouteImport.update({
  id: '/products/cart',
  path: '/products/cart',
  getParentRoute: () => RootLayoutRoute,
} as any)
const RootLayoutProductsIdRoute = RootLayoutProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => RootLayoutRoute,
} as any)
const RootLayoutAuthSignupRoute = RootLayoutAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => RootLayoutAuthRoute,
} as any)
const RootLayoutAuthLoginRoute = RootLayoutAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RootLayoutAuthRoute,
} as any)
const RootLayoutAuthForgetPasswordRoute =
  RootLayoutAuthForgetPasswordRouteImport.update({
    id: '/forget-password',
    path: '/forget-password',
    getParentRoute: () => RootLayoutAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof RootLayoutProfileRouteRouteWithChildren
  '/about': typeof RootLayoutAboutRoute
  '/contact': typeof RootLayoutContactRoute
  '/forget-password': typeof RootLayoutAuthForgetPasswordRoute
  '/login': typeof RootLayoutAuthLoginRoute
  '/signup': typeof RootLayoutAuthSignupRoute
  '/products/$id': typeof RootLayoutProductsIdRoute
  '/products/cart': typeof RootLayoutProductsCartRoute
  '/profile/account': typeof RootLayoutProfileAccountRoute
  '/profile/overview': typeof RootLayoutProfileOverviewRoute
  '/profile/wishlist': typeof RootLayoutProfileWishlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products/': typeof RootLayoutProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof RootLayoutProfileRouteRouteWithChildren
  '/about': typeof RootLayoutAboutRoute
  '/contact': typeof RootLayoutContactRoute
  '/forget-password': typeof RootLayoutAuthForgetPasswordRoute
  '/login': typeof RootLayoutAuthLoginRoute
  '/signup': typeof RootLayoutAuthSignupRoute
  '/products/$id': typeof RootLayoutProductsIdRoute
  '/products/cart': typeof RootLayoutProductsCartRoute
  '/profile/account': typeof RootLayoutProfileAccountRoute
  '/profile/overview': typeof RootLayoutProfileOverviewRoute
  '/profile/wishlist': typeof RootLayoutProfileWishlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products': typeof RootLayoutProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_rootLayout': typeof RootLayoutRouteWithChildren
  '/_rootLayout/profile': typeof RootLayoutProfileRouteRouteWithChildren
  '/_rootLayout/_auth': typeof RootLayoutAuthRouteWithChildren
  '/_rootLayout/about': typeof RootLayoutAboutRoute
  '/_rootLayout/contact': typeof RootLayoutContactRoute
  '/_rootLayout/_auth/forget-password': typeof RootLayoutAuthForgetPasswordRoute
  '/_rootLayout/_auth/login': typeof RootLayoutAuthLoginRoute
  '/_rootLayout/_auth/signup': typeof RootLayoutAuthSignupRoute
  '/_rootLayout/products/$id': typeof RootLayoutProductsIdRoute
  '/_rootLayout/products/cart': typeof RootLayoutProductsCartRoute
  '/_rootLayout/profile/account': typeof RootLayoutProfileAccountRoute
  '/_rootLayout/profile/overview': typeof RootLayoutProfileOverviewRoute
  '/_rootLayout/profile/wishlist': typeof RootLayoutProfileWishlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_rootLayout/products/': typeof RootLayoutProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/about'
    | '/contact'
    | '/forget-password'
    | '/login'
    | '/signup'
    | '/products/$id'
    | '/products/cart'
    | '/profile/account'
    | '/profile/overview'
    | '/profile/wishlist'
    | '/api/auth/$'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/about'
    | '/contact'
    | '/forget-password'
    | '/login'
    | '/signup'
    | '/products/$id'
    | '/products/cart'
    | '/profile/account'
    | '/profile/overview'
    | '/profile/wishlist'
    | '/api/auth/$'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_rootLayout'
    | '/_rootLayout/profile'
    | '/_rootLayout/_auth'
    | '/_rootLayout/about'
    | '/_rootLayout/contact'
    | '/_rootLayout/_auth/forget-password'
    | '/_rootLayout/_auth/login'
    | '/_rootLayout/_auth/signup'
    | '/_rootLayout/products/$id'
    | '/_rootLayout/products/cart'
    | '/_rootLayout/profile/account'
    | '/_rootLayout/profile/overview'
    | '/_rootLayout/profile/wishlist'
    | '/api/auth/$'
    | '/_rootLayout/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RootLayoutRoute: typeof RootLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_rootLayout': {
      id: '/_rootLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rootLayout/contact': {
      id: '/_rootLayout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof RootLayoutContactRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/_rootLayout/about': {
      id: '/_rootLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof RootLayoutAboutRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/_rootLayout/_auth': {
      id: '/_rootLayout/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutAuthRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/_rootLayout/profile': {
      id: '/_rootLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof RootLayoutProfileRouteRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/_rootLayout/products/': {
      id: '/_rootLayout/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof RootLayoutProductsIndexRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rootLayout/profile/wishlist': {
      id: '/_rootLayout/profile/wishlist'
      path: '/wishlist'
      fullPath: '/profile/wishlist'
      preLoaderRoute: typeof RootLayoutProfileWishlistRouteImport
      parentRoute: typeof RootLayoutProfileRouteRoute
    }
    '/_rootLayout/profile/overview': {
      id: '/_rootLayout/profile/overview'
      path: '/overview'
      fullPath: '/profile/overview'
      preLoaderRoute: typeof RootLayoutProfileOverviewRouteImport
      parentRoute: typeof RootLayoutProfileRouteRoute
    }
    '/_rootLayout/profile/account': {
      id: '/_rootLayout/profile/account'
      path: '/account'
      fullPath: '/profile/account'
      preLoaderRoute: typeof RootLayoutProfileAccountRouteImport
      parentRoute: typeof RootLayoutProfileRouteRoute
    }
    '/_rootLayout/products/cart': {
      id: '/_rootLayout/products/cart'
      path: '/products/cart'
      fullPath: '/products/cart'
      preLoaderRoute: typeof RootLayoutProductsCartRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/_rootLayout/products/$id': {
      id: '/_rootLayout/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof RootLayoutProductsIdRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/_rootLayout/_auth/signup': {
      id: '/_rootLayout/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof RootLayoutAuthSignupRouteImport
      parentRoute: typeof RootLayoutAuthRoute
    }
    '/_rootLayout/_auth/login': {
      id: '/_rootLayout/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof RootLayoutAuthLoginRouteImport
      parentRoute: typeof RootLayoutAuthRoute
    }
    '/_rootLayout/_auth/forget-password': {
      id: '/_rootLayout/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof RootLayoutAuthForgetPasswordRouteImport
      parentRoute: typeof RootLayoutAuthRoute
    }
  }
}

interface RootLayoutProfileRouteRouteChildren {
  RootLayoutProfileAccountRoute: typeof RootLayoutProfileAccountRoute
  RootLayoutProfileOverviewRoute: typeof RootLayoutProfileOverviewRoute
  RootLayoutProfileWishlistRoute: typeof RootLayoutProfileWishlistRoute
}

const RootLayoutProfileRouteRouteChildren: RootLayoutProfileRouteRouteChildren =
  {
    RootLayoutProfileAccountRoute: RootLayoutProfileAccountRoute,
    RootLayoutProfileOverviewRoute: RootLayoutProfileOverviewRoute,
    RootLayoutProfileWishlistRoute: RootLayoutProfileWishlistRoute,
  }

const RootLayoutProfileRouteRouteWithChildren =
  RootLayoutProfileRouteRoute._addFileChildren(
    RootLayoutProfileRouteRouteChildren,
  )

interface RootLayoutAuthRouteChildren {
  RootLayoutAuthForgetPasswordRoute: typeof RootLayoutAuthForgetPasswordRoute
  RootLayoutAuthLoginRoute: typeof RootLayoutAuthLoginRoute
  RootLayoutAuthSignupRoute: typeof RootLayoutAuthSignupRoute
}

const RootLayoutAuthRouteChildren: RootLayoutAuthRouteChildren = {
  RootLayoutAuthForgetPasswordRoute: RootLayoutAuthForgetPasswordRoute,
  RootLayoutAuthLoginRoute: RootLayoutAuthLoginRoute,
  RootLayoutAuthSignupRoute: RootLayoutAuthSignupRoute,
}

const RootLayoutAuthRouteWithChildren = RootLayoutAuthRoute._addFileChildren(
  RootLayoutAuthRouteChildren,
)

interface RootLayoutRouteChildren {
  RootLayoutProfileRouteRoute: typeof RootLayoutProfileRouteRouteWithChildren
  RootLayoutAuthRoute: typeof RootLayoutAuthRouteWithChildren
  RootLayoutAboutRoute: typeof RootLayoutAboutRoute
  RootLayoutContactRoute: typeof RootLayoutContactRoute
  RootLayoutProductsIdRoute: typeof RootLayoutProductsIdRoute
  RootLayoutProductsCartRoute: typeof RootLayoutProductsCartRoute
  RootLayoutProductsIndexRoute: typeof RootLayoutProductsIndexRoute
}

const RootLayoutRouteChildren: RootLayoutRouteChildren = {
  RootLayoutProfileRouteRoute: RootLayoutProfileRouteRouteWithChildren,
  RootLayoutAuthRoute: RootLayoutAuthRouteWithChildren,
  RootLayoutAboutRoute: RootLayoutAboutRoute,
  RootLayoutContactRoute: RootLayoutContactRoute,
  RootLayoutProductsIdRoute: RootLayoutProductsIdRoute,
  RootLayoutProductsCartRoute: RootLayoutProductsCartRoute,
  RootLayoutProductsIndexRoute: RootLayoutProductsIndexRoute,
}

const RootLayoutRouteWithChildren = RootLayoutRoute._addFileChildren(
  RootLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RootLayoutRoute: RootLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
